### PR TITLE
Add Howard's blog.

### PR DESCRIPTION
**Pull request by punchagan**

### CODE REVIEW

**Comment by alexott** [comment]
Please, find a way to get only Emacs-related posts for this feed.

**Comment by punchagan** [comment]
I'm not sure there is, though most posts seem to be Emacs related. Closing. /cc @howardabrams

**Comment by howardabrams** [comment]
I'll see if I can built an Emacs-specific RSS feed with my org-mode exports...

**Comment by punchagan** [comment]
I actually spoke too soon. I used a simple Yahoo pipe to get posts which have Emacs either in the title or description. 
Saw an example of this in `en.ini`.

**Comment by punchagan** [comment]
I force pushed a commit, but GitHub doesn't let me reopen the PR.

**Comment by alexott** [comment]
Please, take into account that Yahoo Pipes stop working in September 2015

On Thu, Jun 18, 2015 at 3:39 PM, Puneeth Chaganti <notifications@github.com>
wrote:

> I force pushed a commit, but GitHub doesn't let me reopen the PR.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hober/planet.emacsen.org/pull/56#issuecomment-113160184>
> .
>



-- 
With best wishes,                    Alex Ott
http://alexott.net/
Twitter: alexott_en (English), alexott (Russian)
Skype: alex.ott

**Pull request closed without merging**
